"""
Stock Photo API Wrapper (Unsplash + Pexels)

Tier 1 image source for the pipeline. Primary source for food photography
(recipe pins, lifestyle shots, ingredient flat-lays).

APIs:
- Unsplash: Free, 50 requests/hour
- Pexels: Free, 200 requests/hour

Both APIs are free for commercial use with attribution (handled automatically
via content log tracking).

The wrapper:
1. Takes a search query (generated by Claude via image_search.md prompt)
2. Searches one or both APIs
3. Returns candidate images ranked by relevance
4. Downloads the selected image at the required resolution
5. Tracks image IDs in content-log.jsonl to prevent reuse within 90 days
6. Implements fallback: if one source returns nothing, tries the other

Environment variables required:
- UNSPLASH_ACCESS_KEY
- PEXELS_API_KEY
"""

import os
import logging
from pathlib import Path
from typing import Optional

import requests

logger = logging.getLogger(__name__)

UNSPLASH_BASE_URL = "https://api.unsplash.com"
PEXELS_BASE_URL = "https://api.pexels.com"


class StockPhotoError(Exception):
    """Raised when stock photo search or download fails."""
    pass


class ImageStockAPI:
    """Unified wrapper for Unsplash and Pexels stock photo APIs."""

    def __init__(
        self,
        unsplash_key: Optional[str] = None,
        pexels_key: Optional[str] = None,
    ):
        """
        Initialize stock photo API clients.

        Args:
            unsplash_key: Unsplash access key. Falls back to UNSPLASH_ACCESS_KEY env var.
            pexels_key: Pexels API key. Falls back to PEXELS_API_KEY env var.
        """
        self.unsplash_key = unsplash_key or os.environ.get("UNSPLASH_ACCESS_KEY", "")
        self.pexels_key = pexels_key or os.environ.get("PEXELS_API_KEY", "")

        if not self.unsplash_key:
            logger.warning("UNSPLASH_ACCESS_KEY not set. Unsplash searches will be unavailable.")
        if not self.pexels_key:
            logger.warning("PEXELS_API_KEY not set. Pexels searches will be unavailable.")

        # Rate limit tracking
        self._unsplash_remaining: Optional[int] = None
        self._pexels_remaining: Optional[int] = None

    def search_images(
        self,
        query: str,
        source: str = "both",
        count: int = 5,
        orientation: str = "portrait",
    ) -> list[dict]:
        """
        Search for stock photos. Public interface matching the requirement spec.

        Args:
            query: Search query string.
            source: "unsplash", "pexels", or "both" (default).
            count: Number of results per source.
            orientation: "portrait" (for pins), "landscape", or "squarish".

        Returns:
            list[dict]: Candidate images with standardized fields.
        """
        return self.search(query=query, num_results=count, orientation=orientation,
                           sources=[source] if source != "both" else None)

    def search(
        self,
        query: str,
        num_results: int = 10,
        orientation: str = "portrait",
        sources: Optional[list[str]] = None,
    ) -> list[dict]:
        """
        Search for stock photos across Unsplash and Pexels.

        Implements fallback logic: if the primary source returns no results,
        the other source is tried automatically.

        Args:
            query: Search query (e.g., "overhead shot chicken stir fry vegetables wok").
            num_results: Number of results to return per source.
            orientation: "portrait" (for pins, 2:3), "landscape", or "squarish".
            sources: List of sources to search. Defaults to ["unsplash", "pexels"].

        Returns:
            list[dict]: Candidate images with fields:
                - source: "unsplash" or "pexels"
                - id: Source-specific image ID (for dedup tracking)
                - url: Full-resolution download URL
                - thumbnail_url: Small preview URL for evaluation
                - preview_url: Medium preview URL
                - download_url: Full-resolution download URL
                - width, height: Image dimensions
                - photographer: Attribution info
                - description: Image description from source
        """
        if sources is None:
            sources = []
            if self.unsplash_key:
                sources.append("unsplash")
            if self.pexels_key:
                sources.append("pexels")

        if not sources:
            raise StockPhotoError(
                "No stock photo API keys configured. Set UNSPLASH_ACCESS_KEY and/or PEXELS_API_KEY."
            )

        all_results = []

        for source in sources:
            try:
                if source == "unsplash" and self.unsplash_key:
                    results = self._search_unsplash(query, num_results, orientation)
                    all_results.extend(results)
                elif source == "pexels" and self.pexels_key:
                    results = self._search_pexels(query, num_results, orientation)
                    all_results.extend(results)
                else:
                    logger.warning("Source '%s' not available (missing API key).", source)
            except Exception as e:
                logger.error("Error searching %s: %s", source, e)

        # Fallback: if no results from specified sources, try the other
        if not all_results:
            logger.warning("No results from %s. Trying fallback sources...", sources)
            fallback_sources = []
            if "unsplash" not in sources and self.unsplash_key:
                fallback_sources.append("unsplash")
            if "pexels" not in sources and self.pexels_key:
                fallback_sources.append("pexels")

            for source in fallback_sources:
                try:
                    if source == "unsplash":
                        results = self._search_unsplash(query, num_results, orientation)
                    else:
                        results = self._search_pexels(query, num_results, orientation)
                    all_results.extend(results)
                    if all_results:
                        logger.info("Fallback to %s returned %d results.", source, len(results))
                        break
                except Exception as e:
                    logger.error("Fallback search on %s also failed: %s", source, e)

        logger.info("Stock photo search for '%s': %d total candidates.", query[:50], len(all_results))
        return all_results

    def _search_unsplash(self, query: str, num_results: int, orientation: str) -> list[dict]:
        """
        Search Unsplash API for photos.

        Uses GET /search/photos with orientation=portrait for pin-friendly images.

        Args:
            query: Search query.
            num_results: Number of results to request.
            orientation: Image orientation.

        Returns:
            list[dict]: Standardized image result dicts.
        """
        logger.info("Searching Unsplash: '%s' (orientation=%s, count=%d)", query[:50], orientation, num_results)

        response = requests.get(
            f"{UNSPLASH_BASE_URL}/search/photos",
            headers={"Authorization": f"Client-ID {self.unsplash_key}"},
            params={
                "query": query,
                "per_page": min(num_results, 30),
                "orientation": orientation,
            },
            timeout=15,
        )

        # Track rate limits
        remaining = response.headers.get("X-Ratelimit-Remaining")
        if remaining:
            self._unsplash_remaining = int(remaining)
            if self._unsplash_remaining < 10:
                logger.warning("Unsplash rate limit low: %d requests remaining.", self._unsplash_remaining)

        if response.status_code != 200:
            raise StockPhotoError(f"Unsplash search failed (HTTP {response.status_code}): {response.text}")

        data = response.json()
        results = []

        for photo in data.get("results", []):
            results.append({
                "source": "unsplash",
                "id": f"unsplash:{photo['id']}",
                "url": photo["urls"]["regular"],
                "thumbnail_url": photo["urls"]["thumb"],
                "preview_url": photo["urls"]["small"],
                "download_url": photo["urls"]["full"],
                "width": photo["width"],
                "height": photo["height"],
                "photographer": photo["user"]["name"],
                "photographer_url": photo["user"]["links"]["html"],
                "description": photo.get("description") or photo.get("alt_description") or "",
            })

        logger.info("Unsplash returned %d results for '%s'.", len(results), query[:50])
        return results

    def _search_pexels(self, query: str, num_results: int, orientation: str) -> list[dict]:
        """
        Search Pexels API for photos.

        Uses GET /v1/search with orientation=portrait for pin-friendly images.

        Args:
            query: Search query.
            num_results: Number of results to request.
            orientation: Image orientation.

        Returns:
            list[dict]: Standardized image result dicts.
        """
        logger.info("Searching Pexels: '%s' (orientation=%s, count=%d)", query[:50], orientation, num_results)

        response = requests.get(
            f"{PEXELS_BASE_URL}/v1/search",
            headers={"Authorization": self.pexels_key},
            params={
                "query": query,
                "per_page": min(num_results, 80),
                "orientation": orientation,
            },
            timeout=15,
        )

        # Track rate limits
        remaining = response.headers.get("X-Ratelimit-Remaining")
        if remaining:
            self._pexels_remaining = int(remaining)
            if self._pexels_remaining < 20:
                logger.warning("Pexels rate limit low: %d requests remaining.", self._pexels_remaining)

        if response.status_code != 200:
            raise StockPhotoError(f"Pexels search failed (HTTP {response.status_code}): {response.text}")

        data = response.json()
        results = []

        for photo in data.get("photos", []):
            # Pexels provides multiple sizes -- use 'large' for download, 'medium' for preview
            results.append({
                "source": "pexels",
                "id": f"pexels:{photo['id']}",
                "url": photo["src"]["large2x"],
                "thumbnail_url": photo["src"]["tiny"],
                "preview_url": photo["src"]["medium"],
                "download_url": photo["src"]["original"],
                "width": photo["width"],
                "height": photo["height"],
                "photographer": photo["photographer"],
                "photographer_url": photo.get("photographer_url", ""),
                "description": photo.get("alt") or "",
            })

        logger.info("Pexels returned %d results for '%s'.", len(results), query[:50])
        return results

    def download_image(
        self,
        image: dict,
        output_path: Path,
        width: int = 1000,
    ) -> Path:
        """
        Download a stock photo at the specified width.

        For Unsplash, appends w= parameter to control download width.
        For Pexels, uses the appropriate size URL.

        Args:
            image: Image dict from search results.
            output_path: Path to save the downloaded image.
            width: Target width in pixels (height scales proportionally).

        Returns:
            Path: Path to the downloaded image file.

        Raises:
            StockPhotoError: If download fails.
        """
        source = image.get("source", "")
        download_url = image.get("download_url", image.get("url", ""))

        if not download_url:
            raise StockPhotoError("No download URL available for this image.")

        # Append width parameter for Unsplash URLs
        if source == "unsplash" and "unsplash.com" in download_url:
            separator = "&" if "?" in download_url else "?"
            download_url = f"{download_url}{separator}w={width}"

        logger.info("Downloading image from %s: %s", source, download_url[:80])

        try:
            response = requests.get(download_url, timeout=30, stream=True)
            response.raise_for_status()

            # Ensure output directory exists
            output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)

            with open(output_path, "wb") as f:
                for chunk in response.iter_content(chunk_size=8192):
                    f.write(chunk)

            file_size = output_path.stat().st_size
            logger.info(
                "Image downloaded: %s (%d bytes) -> %s",
                image.get("id", "unknown"), file_size, output_path,
            )
            return output_path

        except requests.RequestException as e:
            raise StockPhotoError(f"Failed to download image: {e}") from e

    def filter_previously_used(
        self,
        candidates: list[dict],
        used_image_ids: list[str],
    ) -> list[dict]:
        """
        Filter out images that have been used in the last 90 days.

        Args:
            candidates: List of candidate images from search.
            used_image_ids: List of image IDs from content-log.jsonl
                            (format: "source:id", e.g., "unsplash:abc123").

        Returns:
            list[dict]: Filtered candidates with previously used images removed.
        """
        if not used_image_ids:
            return candidates

        used_set = set(used_image_ids)
        filtered = [img for img in candidates if img.get("id") not in used_set]

        removed_count = len(candidates) - len(filtered)
        if removed_count > 0:
            logger.info(
                "Filtered out %d previously used images. %d candidates remaining.",
                removed_count, len(filtered),
            )

        return filtered

    def download_thumbnail(self, candidate: dict, timeout: int = 10) -> bytes:
        """
        Download a small thumbnail image for a stock photo candidate.

        Thumbnails are ~200px wide, 5-15KB each. Used for Claude vision
        ranking without downloading full-resolution images.

        Args:
            candidate: Image dict from search results (must have thumbnail_url).
            timeout: Request timeout in seconds.

        Returns:
            bytes: Raw thumbnail image data.

        Raises:
            StockPhotoError: If download fails or no thumbnail URL available.
        """
        thumb_url = candidate.get("thumbnail_url", "")
        if not thumb_url:
            raise StockPhotoError(
                f"No thumbnail URL for candidate {candidate.get('id', 'unknown')}"
            )

        try:
            response = requests.get(thumb_url, timeout=timeout)
            response.raise_for_status()
            logger.debug(
                "Downloaded thumbnail for %s: %d bytes",
                candidate.get("id", "unknown"), len(response.content),
            )
            return response.content
        except requests.RequestException as e:
            raise StockPhotoError(f"Failed to download thumbnail: {e}") from e

    @property
    def rate_limits(self) -> dict:
        """Return current rate limit status for both APIs."""
        return {
            "unsplash_remaining": self._unsplash_remaining,
            "pexels_remaining": self._pexels_remaining,
        }


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    print("Stock Photo API smoke test")
    print("==========================")

    try:
        api = ImageStockAPI()
        results = api.search("overhead shot chicken stir fry vegetables wok")
        print(f"\nFound {len(results)} candidate images:")
        for img in results[:5]:
            print(f"  [{img['source']}] {img['id']}")
            print(f"    {img.get('description', 'N/A')[:80]}")
            print(f"    {img['width']}x{img['height']} by {img['photographer']}")
        print(f"\nRate limits: {api.rate_limits}")
    except StockPhotoError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"Error: {e}")
